### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by gabeweb** [mischat/assessments#1]
Why my profile appears in your code? Are you scraping content for other blogs?

**Comment by Manuelvillalobos30** [comment]
Hola quepasa

**Comment by Manuelvillalobos30** [comment]
> 

Copiando esa persona copia y usa mis datos personales sin consentimiento que debo Aser trabaje con el en una empresa

**Comment by mischat** [comment]
@gabeweb @Manuelvillalobos30 pardon, please let me know what you are talking about ?

**Comment by gabeweb** [comment]
> @gabeweb @Manuelvillalobos30 pardon, please let me know what you are talking about ?

Hey. I don't remember, this was 8 years ago! Maybe was my Tumblr or Blogger blogs. I don't remember now.

**Comment by mischat** [comment]
am sorry, this was a test i was asking people to take, around 11 years ago when they were applying for a backend engineering role in a company where i was the CTO. 

I don't know what you are talking about, there is no code in here ? Where is "your profile". In this task, i asked people to crawl websites, perhaps your personal website was one of them ? Please let me know what it is you are complaining about, and i will try and address.
